### Agregar un Administrador
POST http://localhost:8080/administrators
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTY0OTc3MjgwNCwiaWF0IjoxNjQ5NzM2ODA0fQ.fsZQtH7JeKD5QdM89_6XzW9JaOZJ5rerteTg0EHxkhg

{
  "nombre" : "Nombre Administrador 1",
  "apellido": "Apellido Administrador 1",
  "edad": 20,
  "correoElectronico": "administrador1@gmail.com",
  "password": "Contrasenia Administrador 1",
  "tipoAdministradorId": 1,
  "status": 1
}

### Obtener los Administradores

GET http://localhost:8080/administrators
Content-Type: application/json

### Actualizar un Administrador

PUT http://localhost:8080/administrators/1
Content-Type: application/json

{
  "nombre" : "Nombre Editado Administrador 1",
  "apellido": "Apellido Administrador 1",
  "edad": "20",
  "correoElectronico": "administrador1@gmail.com",
  "password": "Contrasenia Administrador 1",
  "tipoAdministradorId": "1",
  "status": "1"
}

### Borrado Lógico de un Administrador

DELETE http://localhost:8080/administrators/2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTY1MDMzNDMzMCwiaWF0IjoxNjUwMjk4MzMwfQ.xHptMn6ID0vxIFetBjCA6pQ-znDEIHTUcm78v0s990c
Content-Type: application/json

### Borrado Lógico de un Administrador

DELETE http://localhost:8080/products/2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTY1MDMzNDMzMCwiaWF0IjoxNjUwMjk4MzMwfQ.xHptMn6ID0vxIFetBjCA6pQ-znDEIHTUcm78v0s990c
Content-Type: application/json

### Borrado Lógico de un Administrador
GET http://localhost:8080/v2/users/4
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTY1MTc1MTY0NSwiaWF0IjoxNjUxNzE1NjQ1fQ.9BdEDwkFxGL3Pe6MZFKo7SSCFiC6iaFqZ9zyP3dOVcg
Content-Type: application/json