

### Send POST request with json body
POST http://localhost:8080/administrador/login
Content-Type: application/json

{
  "correo": "example@gmail.com",
  "password": "12345678"
}

### Send POST request with json body
POST http://localhost:8080/administrador/login/proveedor
Content-Type: application/json

{
  "correo": "ejemplo@gmail.com",
  "password": "abcd1234"
}