

### Send POST request with json body
POST http://localhost:8080/v2/administrador/login
Content-Type: application/json

{
  "correo": "jupe@gmail.com",
  "password": "123"
}

### Send POST request with json body
POST http://localhost:8080/v2/administrador/login/proveedor
Content-Type: application/json

{
  "correo": "pedromu@gmail.com",
  "password": "456"
}

### Send POST request with json body
POST http://localhost:8080/login/user
Content-Type: application/json

{
  "correo": "exampleU@gmail.com",
  "password": "12345678"
}