### Agregar una categoria
POST http://localhost:8080/categories
Content-Type: application/json

{
  "categoria" : "Categoria 31"
}

### Obtener las categorias

GET http://localhost:8080/categories
Content-Type: application/json