### Agregar una categoria
POST http://localhost:8080/categories
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTY0ODY4MzEwMCwiaWF0IjoxNjQ4NjQ3MTAwfQ.p_IMWrlJAHvp7SfMMOYkz4Fg2B66Wvlvuoyd0b7Gvg8

{
  "categoria" : "Categoria 27"
}

### Obtener las categorias

GET http://localhost:8080/categories
Content-Type: application/json