### GET request with a header
GET http://localhost:8080/v1/example/hello
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTY0ODQ3MDA0MSwiaWF0IjoxNjQ4NDM0MDQxfQ.gckkaAep6WT_VGMINz1AfxluPDreUCahnasmarMd9EE


### Send POST request with json body
POST http://localhost:8080/v1/user/login
Content-Type: application/json

{
  "username": "admin",
  "password": "123",
  "tipoUsuarioId": "1"
}