### Buscar productos por nombre
GET http://localhost:8080/products/productName=pro
Content-Type: application/json

### Listado de productos
GET http://localhost:8080/products
Content-Type: application/json

### Listado de productos por administrador
GET http://localhost:8080/products/idAdmin=1
Content-Type: application/json

### Listado de productos por codigo del producto
GET http://localhost:8080/products/productCode=ABCD1234
Content-Type: application/json

### Agregar un producto
POST http://localhost:8080/products
Content-Type: application/json

{
  "codigoProducto" : "ABCD1234",
  "nombreProducto" : "Nombre",
  "descripcion" : "Descripcion",
  "stock" : 23,
  "precio" : 33.5,
  "colorId" : 1,
  "tallaId" : 1,
  "administradorId": 1,
  "status": 1
}

### Actualizar un producto

PUT http://localhost:8080/products/1
Content-Type: application/json

{
  "codigoProducto" : "ABCD1234",
  "nombreProducto" : "Nombre Editado Producto",
  "descripcion" : "Descripcion",
  "stock" : 23,
  "precio" : 33.5,
  "colorId" : 1,
  "tallaId" : 1,
  "administradorId": 1,
  "status": 1
}
### Eliminar un producto
DELETE http://localhost:8080/products/1



### Eliminar un producto
PUT http://localhost:8080/v2/productDescriptions/productId=71/stock=25
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTY1Mzk4ODExNCwiaWF0IjoxNjUzOTUyMTE0fQ.WrHP3n_tN1fJGdHfLgMLqclkJ0AoHFfFy_QAnXwk7Ew
Content-Type: application/json

### Eliminar un producto
GET http://localhost:8080/v2/productDescriptions/productId=71
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTY1Mzk4ODExNCwiaWF0IjoxNjUzOTUyMTE0fQ.WrHP3n_tN1fJGdHfLgMLqclkJ0AoHFfFy_QAnXwk7Ew
Content-Type: application/json