### Agregar una Talla
POST http://localhost:8080/sizes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTY0ODY0Mjk3NSwiaWF0IjoxNjQ4NjA2OTc1fQ.iYoUkHm6_LGpSy0Z-cO8LZUPDBxNapMAXJvVR3WA-cg

{
  "nombreTalla" : "Talla 2"
}

### Obtener las Tallas

GET http://localhost:8080/sizes
Content-Type: application/json

### Actualizar una Talla

PUT http://localhost:8080/sizes/1
Content-Type: application/json

{
  "descripcion" : "Talla 1"
}

### Borrado Fisico de una Talla

DELETE http://localhost:8080/sizes/2
Content-Type: application/json
