INSERT INTO color (id, descripcion) VALUES (1,'Negro');
INSERT INTO color (id, descripcion) VALUES (2,'Azul');
INSERT INTO color (id, descripcion) VALUES (3,'Marron');
INSERT INTO color (id, descripcion) VALUES (4,'Gris');
INSERT INTO color (id, descripcion) VALUES (5,'Verde');
INSERT INTO color (id, descripcion) VALUES (6,'Naranja');
INSERT INTO color (id, descripcion) VALUES (7,'Rosa');
INSERT INTO color (id, descripcion) VALUES (8,'Purpura');
INSERT INTO color (id, descripcion) VALUES (9,'Rojo');
INSERT INTO color (id, descripcion) VALUES (10,'Blanco');
INSERT INTO color (id, descripcion) VALUES (11,'Amarillo');
INSERT INTO color (id, descripcion) VALUES (12,'Turquesa');
INSERT INTO color (id, descripcion) VALUES (13,'Verde oliva');
INSERT INTO color (id, descripcion) VALUES (14,'Verde Menta');
INSERT INTO color (id, descripcion) VALUES (15,'Lavanda');
INSERT INTO color (id, descripcion) VALUES (16,'Magenta');
INSERT INTO color (id, descripcion) VALUES (17,'Salmon');
INSERT INTO color (id, descripcion) VALUES (18,'Cian');
INSERT INTO color (id, descripcion) VALUES (19,'Beige');
INSERT INTO color (id, descripcion) VALUES (20,'Rosado');
INSERT INTO color (id, descripcion) VALUES (21,'Verde oscuro');
INSERT INTO color (id, descripcion) VALUES (22,'Lila');
INSERT INTO color (id, descripcion) VALUES (23,'Amarillo pálido');
INSERT INTO color (id, descripcion) VALUES (24,'Fucsia');
INSERT INTO color (id, descripcion) VALUES (25,'Mostaza');
INSERT INTO color (id, descripcion) VALUES (26,'Ocre');
INSERT INTO color (id, descripcion) VALUES (27,'Verde claro');
INSERT INTO color (id, descripcion) VALUES (28,'Azul claro');
INSERT INTO color (id, descripcion) VALUES (29,'Borgoña');
INSERT INTO color (id, descripcion) VALUES (30,'Trullo');
INSERT INTO color (id, descripcion) VALUES (31,'Verde aceituna');
INSERT INTO color (id, descripcion) VALUES (32,'Malva');
INSERT INTO color (id, descripcion) VALUES (33,'Purpura oscuro');
INSERT INTO color (id, descripcion) VALUES (34,'Verde lima');
INSERT INTO color (id, descripcion) VALUES (35,'Ciruela');
INSERT INTO color (id, descripcion) VALUES (36,'Melocoton');
INSERT INTO color (id, descripcion) VALUES (37,'Violeta');
INSERT INTO color (id, descripcion) VALUES (38,'Tan');
INSERT INTO color (id, descripcion) VALUES (39,'Granate');
